### ISSUE TITLE
Failure to load xdp program

### ISSUE THREAD

**Issue by NirGeller18** [xdp-project/xdp-tools#238] opened 2022-11-20 12:55 UTC
Hi there,

I've been using xdp-tools successfully for a while now on kernel 5.10 running on arm8.
I had to migrate to kernel 5.15.60 and now I can't load a simple xdp program:

libbpf: Error in bpf_object__probe_loading():Invalid argument(22). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value

Of course the kernel is compiled with BPF_SYSCALL and I'm setting RLIMIT to infinity with:
ulimit -l unlimited

I tried cloning the recent xdp-tools, and checkout out the libbpf it is supplied with. Same result.

Can you assist?

Thanks a lot,

Nir.

**Comment by NirGeller18** [comment] 2022-11-20 13:17
Output of strace:
...
...
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_SOCKET_FILTER, insn_cnt=2, insns=0xffffe2a74130, license="GPL", log_level=0, log_size=0, log_buf=NULL, kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS, prog_btf_fd=0, func_info_rec_size=0, func_info=NULL, func_info_cnt=0, line_info_rec_size=0, line_info=NULL, line_info_cnt=0, attach_btf_id=0, attach_prog_fd=0}, 116) = -1 ENOENT (No such file or directory)
prlimit64(0, RLIMIT_MEMLOCK, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}, NULL) = 0
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_SOCKET_FILTER, insn_cnt=2, insns=0xffffe2a74340, license="GPL", log_level=0, log_size=0, log_buf=NULL, kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS, prog_btf_fd=0, func_info_rec_size=0, func_info=NULL, func_info_cnt=0, line_info_rec_size=0, line_info=NULL, line_info_cnt=0, attach_btf_id=0, attach_prog_fd=0, fd_array=NULL}, 128) = -1 ENOENT (No such file or directory)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_TRACEPOINT, insn_cnt=2, insns=0xffffe2a74340, license="GPL", log_level=0, log_size=0, log_buf=NULL, kern_version=KERNEL_VERSION(0, 0, 0), prog_flags=0, prog_name="", prog_ifindex=0, expected_attach_type=BPF_CGROUP_INET_INGRESS, prog_btf_fd=0, func_info_rec_size=0, func_info=NULL, func_info_cnt=0, line_info_rec_size=0, line_info=NULL, line_info_cnt=0, attach_btf_id=0, attach_prog_fd=0, fd_array=NULL}, 128) = -1 EINVAL (Invalid argument)
write(2, "libbpf: Error in bpf_object__pro"..., 215libbpf: Error in bpf_object__probe_loading():Invalid argument(22). Couldn't load trivial BPF program. Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.
...
...


bpf(BPF_PROG_LOAD.. returning -1 ?

**Comment by tohojo** [comment] 2022-11-21 13:00
Did you compile the kernel yourself? If so, this could be a kconfig
issue? Is CONFIG_BPF_EVENTS set?

**Comment by NirGeller18** [comment] 2022-11-21 17:47
Hi,
I'm working on a Yocto project. I recompiled with CONFIG_BPF_EVENTS, same result....

**Comment by tohojo** [comment] 2022-11-22 11:04
NirGeller18 ***@***.***> writes:

> Hi,
> I'm working on a Yocto project. I recompiled with CONFIG_BPF_EVENTS, same result....

Hmm, there could be other configs, I suppose? You could take a look at
the list of config options in tools/testing/selftests/bpf/config and see
if any of those are missing and try to enable them (you may not want all
of them in your production build, but to at least see if it's related)?

You could also try to use retsnoop to figure out where the failure is
actually coming from: https://github.com/anakryiko/retsnoop

**Comment by tohojo** [comment] 2022-11-23 23:44
NirGeller18 ***@***.***> writes:

> Here's a dipper trace. I suspect the problem has something to do with memory allocation.
> In bpf_check(), is vzalloc() failing?
> [prog_load_ftrace_1.txt](https://github.com/xdp-project/xdp-tools/files/10077671/prog_load_ftrace_1.txt)

Hmm, could be? BPF memory management moved from rlimit to memcg-based;
don't recall the exact kernel version the switchover happened, but could
be related if you're seeing memory allocation failures?

**Comment by NirGeller18** [comment] 2022-11-24 09:05
Well, I really have no idea about that. I can tell you that I have another device running kernel 5.15.32 on which I experience no problem with XDP.

Is there anything I can do about that memory management issue? Anything to check or test?

**Comment by NirGeller18** [comment] 2022-11-24 11:26
If bpf is reliant on memcg, does this mean that CONFIG_MEMCG needs to be enabled?

I'm running a preempt_rt patched kernel, and in the menuconfig I see that it contradicts MEMCG:

Symbol: MEMCG [=n]                                                                              │
  │ Type  : bool                                                                                    │
  │ Defined at init/Kconfig:944                                                                     │
  │   Prompt: Memory controller                                                                     │
  │   Depends on: CGROUPS [=y] && !PREEMPT_RT [=y]

?

**Comment by tohojo** [comment] 2022-11-24 13:57
NirGeller18 ***@***.***> writes:

> If bpf is reliant on memcg, does this mean that CONFIG_MEMCG needs to be enabled?
>
> I'm running a preempt_rt patched kernel, and in the menuconfig I see that it contradicts MEMCG:
>
> Symbol: MEMCG [=n]                                                                              │
>   │ Type  : bool                                                                                    │
>   │ Defined at init/Kconfig:944                                                                     │
>   │   Prompt: Memory controller                                                                     │
>   │   Depends on: CGROUPS [=y] && !PREEMPT_RT [=y]
>
> ?

Hmm, it looks like the accounting is just skipped entirely if memcg is
not compiled in:

https://elixir.bootlin.com/linux/latest/source/kernel/bpf/syscall.c#L488

So that shouldn't be the issue here. Also, the internal memory
allocations in the verifier are just regular kmalloc() calls, so if they
are failing that's definitely a different issue.

Maybe your system just has trouble fulfilling kmalloc() requests or
something? The struct bpf_verifier_env is almost 8k, so if the system is
very memory-constrained it may not be able to find a consecutive chunk
that big?

**Comment by NirGeller18** [comment] 2022-11-24 13:59
This is probably not the issue. When running kernel 5.10.109 everything worked just fine...
I have 2GB RAM on the device

**Comment by tohojo** [comment] 2022-11-24 14:33
NirGeller18 ***@***.***> writes:

> This is probably not the issue. When running kernel 5.10.109 everything worked just fine...
> I have 2GB RAM on the device

Ah, actually looking at your trace again I don't think it's a memory
allocation failure. In your trace, bpf_check() does:

- ktime_get():
  https://elixir.bootlin.com/linux/v5.15.60/source/kernel/bpf/verifier.c#L13704
- kmem_cache_alloc_trace (that's kzalloc):
  https://elixir.bootlin.com/linux/v5.15.60/source/kernel/bpf/verifier.c#L13717
- vzalloc():
  https://elixir.bootlin.com/linux/v5.15.60/source/kernel/bpf/verifier.c#L13724
- capable():
  https://elixir.bootlin.com/linux/v5.15.60/source/kernel/bpf/verifier.c#L13733

Meaning it gets past the allocations, and it's not them failing that's
the issue. Then it does verbose() and kvfree(), which means it must be
hitting this branch:

https://elixir.bootlin.com/linux/v5.15.60/source/kernel/bpf/verifier.c#L13758

Which could happen if your kernel does not have BTF information compiled
in. Does it? :)

**Comment by NirGeller18** [comment] 2022-11-24 14:37
Actually, I do have CONFIG_DEBUG_INFO_BTF=y enabled in the kernel config, and I don't see the message 
"in-kernel BTF is malformed" in dmesg...

**Comment by tohojo** [comment] 2022-11-24 14:46
NirGeller18 ***@***.***> writes:

> Actually, I do have CONFIG_DEBUG_INFO_BTF=y enabled in the kernel config, and I don't see the message 
> "in-kernel BTF is malformed" in dmesg...

That message doesn't go to dmesg, it goes to the verifier log (which I'm
not sure if libbpf outputs anywhere for the feature probing loads).

Do you have a /sys/kernel/btf/vmlinux files on the host? Can you dump it
with bpftool (`bpftool btf dump file /sys/kernel/btf/vmlinux`)?

**Comment by tohojo** [comment] 2022-11-24 22:41
NirGeller18 ***@***.***> writes:

> Here's the btf dump file
> [btf_dump_file.txt](https://github.com/xdp-project/xdp-tools/files/10085774/btf_dump_file.txt)

Hmm, that looks normal enough (it's half the size than the one on my
machine, but that's probably because your kernel is smaller?). I don't
really see any other way bpf_check() could end up doing that sequence of
calls, though; if the execution continues there should be another
capable() check, and further allocations.

You could try checking the return value of bpf_get_btf_vmlinux() to see
if there is indeed an issue with this. This can be done with bpftrace,
like:

bpftrace -e 'kretprobe:bpf_get_btf_vmlinux { printf("%p\n", retval); }'

While that is running, try loading a BPF program in another terminal,
and see what bpftrace outputs when you do that.

Oh, and what happens if you run 'bpftool map' or 'bpftool prog'? Both of
those should load a BPF iterator program; does that work?

**Comment by NirGeller18** [comment] 2022-11-25 09:42
You might be right about the BTF information:

# bpftrace -ve 'kretprobe:bpf_get_btf_vmlinux { printf("%p\n", retval); }'
INFO: node count: 7
Attaching 1 probe...

Error log:
in-kernel BTF is malformed
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

ERROR: Error loading program: kretprobe:bpf_get_btf_vmlinux

**Comment by NirGeller18** [comment] 2022-11-25 10:21
Yep, I confirmed that the code drops into:

kernel/bpf/verifier.c,  line 13,756:

if (IS_ERR(btf_vmlinux)) {
	/* Either gcc or pahole or kernel are broken. */
	verbose(env, "in-kernel BTF is malformed\n");
	ret = PTR_ERR(btf_vmlinux);
	goto skip_full_check;
}

Is there anything I can do about this? Test? check?

**Comment by tohojo** [comment] 2022-11-25 15:43
NirGeller18 ***@***.***> writes:

> Yep, I confirmed that the code drops into:
>
> kernel/bpf/verifier.c,  line 13,756:
>
> if (IS_ERR(btf_vmlinux)) {
> 	/* Either gcc or pahole or kernel are broken. */
> 	verbose(env, "in-kernel BTF is malformed\n");
> 	ret = PTR_ERR(btf_vmlinux);
> 	goto skip_full_check;
> }
>
> Is there anything I can do about this? Test? check?

So since you mentioned it's a Yocto project, my guess would be that
there's some issue in the build tooling there. To generate the BTF at
build time you'll need at least an up-to-date version of the 'pahole'
utility. So maybe it's just that?

**Comment by tohojo** [comment] 2022-11-29 18:31
Closing this as it seems to be a kernel issue and not a bug in xdp-tools

**Closed by tohojo** 2022-11-29 18:31 UTC

**Comment by tohojo** [comment] 2022-11-30 13:06
Cool - you're welcome! :)
