### ISSUE TITLE
libxdp: Error attaching XDP program to ifindex 13: Out of memory

### ISSUE THREAD

**Issue by calvin2021y** [xdp-project/xdp-tools#333] opened 2023-06-12 14:05 UTC
```sh
xdp-filter load ens1f1v3 -f tcp -v
Current rlimit 16859971584 already >= minimum 1048576
Couldn't open pin directory /sys/fs/bpf/xdp-filter/programs/ens1f1v3: No such file or directory
Looking for eBPF program with features tcp,allow
Found prog 'xdpfilt_alw_tcp.o' matching feature set to be loaded on interface 'ens1f1v3'.
libxdp: Error attaching XDP program to ifindex 13: Out of memory
Couldn't attach XDP program on iface 'ens1f1v3': Out of memory(-12)

```
kernel is  6.1.27, NIC is BCM57416

**Comment by tohojo** [comment] 2023-06-12 14:59
This looks like it's a driver error. AFAICT there should be an
accompanying warning in dmesg?

**Comment by tohojo** [comment] 2023-06-19 10:33
Yup, definitely a driver configuration issue! Think you may have to mess around with the "channels" configuration in ethtool? It's not a bug in xdp-tools at least, so closing this issue :)

**Closed by tohojo** 2023-06-19 10:33 UTC
